[package]
name = "securestore"
version = "0.1.0"
authors = ["Mahmoud Al-Qudsi <mqudsi@neosmart.net>"]
edition = "2018"

[dependencies]
base64 = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[target.'cfg(not(windows))'.dependencies.openssl]
version = "0.10"
features = [ ]

[target.'cfg(windows)'.dependencies.openssl]
version = "0.10"
features = [ "vendored" ]

[features]
# default = [ "openssl-vendored" ]
openssl-vendored = [ "openssl/vendored" ]

[dev-dependencies]
tempfile = "3.1"
