[package]
name = "ssclient"
version = "0.1.0"
authors = ["Mahmoud Al-Qudsi <mqudsi@neosmart.net>"]
edition = "2018"

[dependencies]
atty = "0.2"
clap = { version = "2.33", default-features = false }
securestore = { path = "../securestore" }
serde_json = "1.0"
getch = "0.2"
